name: Bug AI Workflow
on:
  issues:
    types: [opened, edited]

jobs:
  BugWorkflow:
    runs-on: ubuntu-latest
    
    if: github.event_name == 'issues' &&
      (github.event.action == 'opened' || github.event.action == 'edited') && 
      contains(github.event.issue.title, '[BugAI]')

    steps:
      - name: Check out scripts
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4

      - name: Parse Issue JSON
        id: parse_issue_json
        shell: pwsh        
        run: |
          # Parse Issue Body
          
          "${{ github.event.issue.body }}"
          import-module Microsoft.PowerShell.Utility
          $issuebody = ConvertFrom-Markdown -InputObject "${{ github.event.issue.body }}"
          $xmlbody = ([xml]"<xml>$($issuebody.Html)</xml>").xml
          foreach ($heading in $xmlbody.h3) {
            $variablename = $heading.id
            switch ($heading.NextSibling.Name) {
              "p" {
                $variablevalue = $heading.NextSibling.InnerText
              }         
              "ul" {
                $variablevalue = ($heading.NextSibling.li | where {$_.childnodes.checked -eq 'checked'} | foreach-object {$_.'#text'.trim()}) -join ','
              }
            }
            write-host "$($variablename) = $($variablevalue)"
            Write-Output "$($variablename)=$($variablevalue)" >> $Env:GITHUB_OUTPUT
          }
      - name: Feedback Issue
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        uses: actions/github-script@v6
        with:
          script: |
            var commentBody = "👋 @${{ github.event.issue.user.login }} Thank for rasing this up. we will look into this ASAP."
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            })
      - name: Google Gemini Action
        shell: pwsh
        run: |
          $what-happened="${{ steps.parse_issue_json.outputs.what-happened }}"
          curl \
          -H 'Content-Type: application/json' \
          -d "{\"contents\":[{\"parts\":[{\"text\":\"$what_happened\"}]}]}" \
          -X POST 'https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent?key=${{ secrets.GEMINI_API_KEY }}'
            
      - name: Close issue
        id: close_issue
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        shell: pwsh        
        run: |
          # Close Issue
            cd $env:GITHUB_WORKSPACE
            gh issue close --comment "@${{ github.event.issue.user.login }} This issue has been resloved." "${{ github.event.issue.number }}"
