name: QR code Genrator Workflow
on:
  issues:
    types: [opened, edited]

jobs:
  BugWorkflow:
    runs-on: ubuntu-latest
    
    if: github.event_name == 'issues' &&
      (github.event.action == 'opened' || github.event.action == 'edited') && 
      contains(github.event.issue.title, '[QRCode]')

    steps:
      - name: Check out scripts
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
